export const names = [
  "Anita Cheng",
  "Ella Sanfilippo",
  "Amy Hu",
  "Amanda Wen",
  "Julia Kasper",
  "Michael DiGiovanna",
  "Saera Kim",
  "Minjoo Kim",
  "Nayana Balusu",
  "Brooke Schwartz",
  "Gwen Toll",
  "Sueah Kim",
  "Lea DeVylder",
  "Katrina Darms",
  "Sydney Sun",
  "Clarine Lee",
  "Anika Bhagavatula",
  "Hazel Froling",
  "Grace Kolosek",
  "Celine Min",
  "Maya Galindo Benson",
  "Nicole Huang",
  "Sukie Wang",
  "Jackson Underwood",
  "Rayya Gracy",
  "Graana Khan",
  "Camellia Wang",
  "Lily Du",
  "Christy Zo",
  "Heysu Oh",
  "Sophia Hao",
  "Shannon Lee",
  "Sophie Heap",
  "Leslie Lin",
  "Yuer Zhu",
  "Dion Lewis",
  "Michele Hratko",
  "Joanna Ni",
  "Phoebe Lee",
  "Shannon Lin",
  "Jeffrey Ye",
  "Aarnav Patel",
  "Jing Peng",
  "Mason Wang",
  "Suanna Zhong",
  "Erin Hsu",
  "Eunice Lai",
  "Perry Chen",
  "Oscar Wang",
  "Matthew Akuamoah-Boateng",
  "Nicholas Baek",
  "Sherry Chen",
  "Yon Maor",
  "Chris Song",
  "Stacy Chen",
  "Ayden Xu",
  "Ervin Song",
  "Viviana Staicu",
  "Eric Lin",
  "Minsung Kang",
  "A Chair",
  "Jeffrey Zhang",
  "Brooke Gunter",
  "Anna Gerchanovsky",
  "Yanina Shavialenka",
  "Andrew Zhou",
  "Marissa Fernandez",
  "Timothy Kim",
  "Maya Ousachi",
  "Elizabeth Hager",
  "Joy Leung",
  "Kevin Tong",
  "Dunn Zhang",
  "Destini Brown-Greene",
  "Mildred Amofa",
  "Lucy Hwang",
  "Jocelyn Su",
  "Caroline LaPiana",
  "Sally Pak",
  "Dhruti Kuchibhotla",
  "Olu-Banke Boakye-Yiadom",
  "Lillian Hao",
  "Peggy Shen",
  "Angela Huang",
  "Jiaxin Lin",
  "Joelle Lee",
  "Kirsten Park",
  "Jisoo Han",
  "Vera Zhong",
  "Fran Stedman",
  "Alisa Lo",
  "Saanika Chauk",
  "Kaitlyn Xie",
  "Lianna Huang",
  "Chase Gumbs",
  "AJ Seo",
  "Helen Huang",
  "Kelly Dam",
  "Yujun Wu",
  "Cindy Liu",
  "Joanna Ge",
  "Fran Stedman",
  "Smriti Chopra",
  "Hanna Luo",
  "Annika Wu",
  "Alice Anie",
  "Kate Lee",
  "Sharon Ren",
  "Sophia Hoch",
  "Caroline Michalow",
  "YuXi Lee",
  "Lauren LoriaSklar",
  "Samantha Vu",
  "Ianca DeLosSantos",
  "Lily Stern",
  "Vera Mazeeva",
  "Audrey Shao",
  "Brooklyn Mao",
  "Rebecca Jiang",
  "Roy Park",
  "Kyli Hilaire",
  "Elva Jia",
  "Annika Wu",
  "Yikun Yang",
  "Sowang Kundeling",
  "Yeajoo Cho",
  "Vivian Liu",
  "Alice Yu",
  "Esha Shah",
  "Maggie Guo",
  "Karina Halevy",
  "Jasper Gitlitz",
  "Katherine Wang",
  "Felix Gabriel",
  "Harry Schneider",
  "Nick Barreto",
  "Will Berick",
  "Erica Fu",
  "Maddie Burroughs",
  "Aidan Hong",
  "Chelsea Tang",
  "Erin Choi",
  "Kate Lee",
  "Susan Ni",
  "Yuktha Vemula",
  "Astha Shah",
  "Lucy Gunther",
  "Rianna Campbell",
  "Eliseea Faur",
  "Rui Wang",
  "Peiran Ge",
  "Jennifer Zhou",
  "Minjin Batzorig",
  "Tippi Li",
  "Annie Woo",
  "Dani Preston",
  "Layla Malhas",
  "Jessica Lai",
  "Grace Liao",
  "Mairssa Lee",
  "Sulli Yatabe",
  "Sulli Yatabe",
];

export const team = [
  "Co-Producer\n│      ├─   Model",
  "Co-Producer",
  "Head of Design",
  "Design Coordinator",
  "Designer \n│      ├─  Coordinator",
  "Designer \n│      ├─  Coordinator",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer and PR",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Co-Head of Creative",
  "Co-Head of Creative",
  "Co-Head of Print",
  "Co-Head of Print",
  "Print member",
  "Print member\n│      ├─   Dance",
  "Print member",
  "Print member",
  "print member",
  "Motion Member",
  "Head of Motion",
  "Motion Member",
  "Motion Member",
  "Motion Member",
  "Motion Member",
  "Chair",
  "Head of Photo",
  "Photo Member",
  "Photo Member",
  "Photo Member",
  "Photo Member",
  "Photo Member",
  "Photo Member",
  "Photo Member",
  "Head of Web",
  "Web Team",
  "Web Team",
  "Web Team",
  "Web Team",
  "Web Tea",
  "Web Team",
  "Web Team",
  "Chair",
  "Co-Head of Model",
  "Co-Head of Model",
  "Model Coordinator",
  "Model",
  "Model\n│      ├─  Finance Assistant",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Head of Public Relations",
  "Co-Head of Digital Marketing",
  "Co-Head of Digital Marketing",
  "Digital Marketing Member",
  "Sponsorships Team Member",
  "Sponsorships Team Member",
  "Head of Dance",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dance Assistant",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Co-Head of Production",
  "Co-Head of Production",
  "Head of Box Office",
  "Box Office Coordinator",
  "Box Office Coordinator",
  "Box Office Coordinator",
  "Lighting Designer\n│      ├─  Dancer",
  "Lighting Designer\n│      ├─  SM Support",
  "Head of Sound Design\n│      ├─  Model",
  "Sound Designer",
  "Sound Designer",
  "Sound Designer",
  "Sound Designer",
  "Co-Head of Stage Design\n│      ├─  Hair/Makeup",
  "Co-Head of Stage Design",
  "Stage Designer",
  "Stage Designer",
  "Stage Designer",
  "Stage Designer",
  "Stage Designer",
  "Stage Designer",
  "Stage Manager",
  "Stage Manager",
  "Stage Manager",
  "Lighting Designer",
  "Co-Head of Cinematography",
  "Co-Head of Cinematography",
  "Cinematographer",
  "Cinematographer",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
];
export const title = [
  "Executive",
  "Executive",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "PR",
  "PR",
  "PR",
  "PR",
  "PR",
  "PR",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Cinematography",
  "Cinematography",
  "Cinematography",
  "Cinematography",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
];
export const urls = [
  "/../../src/headshots/Executive_AnitaCheng.webp",
  "/../../src/headshots/Executive_EllaSanfilippo.webp",
  "/../../src/headshots/Design_AmyHu.webp",
  "/../../src/headshots/Design_AmandaWen.webp",
  "/../../src/headshots/Design_JuliaKasper.webp",
  "/../../src/headshots/Design_MichaelDiGiovanna.webp",
  "/../../src/headshots/Design_SaeraKim.webp",
  "/../../src/headshots/Design_MinjooKim.webp",
  "/../../src/headshots/Design_NayanaBalusu.webp",
  "/../../src/headshots/Design_BrookeSchwartz.webp",
  "/../../src/headshots/Design_GwenToll.webp",
  "/../../src/headshots/Design_SueahKim.webp",
  "/../../src/headshots/Design_LeaDeVylder.webp",
  "/../../src/headshots/Design_KatrinaDarms.webp",
  "/../../src/headshots/Design_SydneySun.webp",
  "/../../src/headshots/Design_ClarineLee.webp",
  "/../../src/headshots/Design_AnikaBhagavatula.webp",
  "/../../src/headshots/Design_HazelFroling.webp",
  "/../../src/headshots/Design_GraceKolosek.webp",
  "/../../src/headshots/Design_CelineMin.webp",
  "/../../src/headshots/Design_MayaGalindo Benson.webp",
  "/../../src/headshots/Design_NicoleHuang.webp",
  "/../../src/headshots/Design_SukieWang.webp",
  "/../../src/headshots/Design_JacksonUnderwood.webp",
  "/../../src/headshots/Design_RayyaGracy.webp",
  "/../../src/headshots/Design_GraanaKhan.webp",
  "/../../src/headshots/Design_CamelliaWang.webp",
  "/../../src/headshots/Design_LilyDu.webp",
  "/../../src/headshots/Creative_ChristyZo.webp",
  "/../../src/headshots/Creative_HeysuOh.webp",
  "/../../src/headshots/Creative_SophiaHao.webp",
  "/../../src/headshots/Creative_ShannonLee.webp",
  "/../../src/headshots/Creative_SophieHeap.webp",
  "/../../src/headshots/Creative_LeslieLin.webp",
  "/../../src/headshots/Creative_YuerZhu.webp",
  "/../../src/headshots/Creative_DionLewis.webp",
  "/../../src/headshots/Creative_MicheleHratko.webp",
  "/../../src/headshots/Creative_JoannaNi.webp",
  "/../../src/headshots/Creative_PhoebeLee.webp",
  "/../../src/headshots/Creative_ShannonLin.webp",
  "/../../src/headshots/Creative_JeffreyYe.webp",
  "/../../src/headshots/Creative_AarnavPatel.webp",
  "/../../src/headshots/Creative_JingPeng.webp",
  "/../../src/headshots/Creative_MasonWang.webp",
  "/../../src/headshots/Creative_SuannaZhong.webp",
  "/../../src/headshots/Creative_ErinHsu.webp",
  "/../../src/headshots/Creative_EuniceLai.webp",
  "/../../src/headshots/Creative_PerryChen.webp",
  "/../../src/headshots/Creative_OscarWang.webp",
  "/../../src/headshots/Creative_MatthewAkuamoah-Boateng.webp",
  "/../../src/headshots/Creative_NicholasBaek.webp",
  "/../../src/headshots/Creative_SherryChen.webp",
  "/../../src/headshots/Creative_YonMaor.webp",
  "/../../src/headshots/Creative_ChrisSong.webp",
  "/../../src/headshots/Creative_StacyChen.webp",
  "/../../src/headshots/Creative_AydenXu.webp",
  "/../../src/headshots/Creative_ErvinSong.webp",
  "/../../src/headshots/Creative_VivianaStaicu.webp",
  "/../../src/headshots/Creative_EricLin.webp",
  "/../../src/headshots/Creative_MinsungKang.webp",
  "/../../src/headshots/Creative_AChair.webp",
  "/../../src/headshots/Model_JeffreyZhang.webp",
  "/../../src/headshots/Model_BrookeGunter.webp",
  "/../../src/headshots/Model_AnnaGerchanovsky.webp",
  "/../../src/headshots/Model_YaninaShavialenka.webp",
  "/../../src/headshots/Model_AndrewZhou.webp",
  "/../../src/headshots/Model_MarissaFernandez.webp",
  "/../../src/headshots/Model_TimothyKim.webp",
  "/../../src/headshots/Model_MayaOusachi.webp",
  "/../../src/headshots/Model_ElizabethHager.webp",
  "/../../src/headshots/Model_JoyLeung.webp",
  "/../../src/headshots/Model_KevinTong.webp",
  "/../../src/headshots/Model_DunnZhang.webp",
  "/../../src/headshots/Model_DestiniBrown-Greene.webp",
  "/../../src/headshots/Model_MildredAmofa.webp",
  "/../../src/headshots/Model_LucyHwang.webp",
  "/../../src/headshots/Model_JocelynSu.webp",
  "/../../src/headshots/Model_CarolineLaPiana.webp",
  "/../../src/headshots/Model_SallyPak.webp",
  "/../../src/headshots/Model_DhrutiKuchibhotla.webp",
  "/../../src/headshots/Model_Olu-BankeBoakye-Yiadom.webp",
  "/../../src/headshots/PR_LillianHao.webp",
  "/../../src/headshots/PR_PeggyShen.webp",
  "/../../src/headshots/PR_AngelaHuang.webp",
  "/../../src/headshots/PR_JiaxinLin.webp",
  "/../../src/headshots/PR_JoelleLee.webp",
  "/../../src/headshots/PR_KirstenPark.webp",
  "/../../src/headshots/Dance_JisooHan.webp",
  "/../../src/headshots/Dance_VeraZhong.webp",
  "/../../src/headshots/Dance_FranStedman.webp",
  "/../../src/headshots/Dance_AlisaLo.webp",
  "/../../src/headshots/Dance_SaanikaChauk.webp",
  "/../../src/headshots/Dance_KaitlynXie.webp",
  "/../../src/headshots/Dance_LiannaHuang.webp",
  "/../../src/headshots/Dance_ChaseGumbs.webp",
  "/../../src/headshots/Dance_AJSeo.webp",
  "/../../src/headshots/Dance_HelenHuang.webp",
  "/../../src/headshots/Dance_KellyDam.webp",
  "/../../src/headshots/Dance_YujunWu.webp",
  "/../../src/headshots/Dance_CindyLiu.webp",
  "/../../src/headshots/Dance_JoannaGe.webp",
  "/../../src/headshots/Dance_FranStedman.webp",
  "/../../src/headshots/Dance_SmritiChopra.webp",
  "/../../src/headshots/Dance_HannaLuo.webp",
  "/../../src/headshots/Dance_AnnikaWu.webp",
  "/../../src/headshots/Dance_AliceAnie.webp",
  "/../../src/headshots/Dance_KateLee.webp",
  "/../../src/headshots/Dance_SharonRen.webp",
  "/../../src/headshots/Dance_SophiaHoch.webp",
  "/../../src/headshots/Dance_CarolineMichalow.webp",
  "/../../src/headshots/Dance_YuXiLee.webp",
  "/../../src/headshots/Dance_LaurenLoriaSklar.webp",
  "/../../src/headshots/Dance_SamanthaVu.webp",
  "/../../src/headshots/Dance_IancaDeLosSantos.webp",
  "/../../src/headshots/Dance_LilyStern.webp",
  "/../../src/headshots/Dance_VeraMazeeva.webp",
  "/../../src/headshots/Dance_AudreyShao.webp",
  "/../../src/headshots/Dance_BrooklynMao.webp",
  "/../../src/headshots/Dance_RebeccaJiang.webp",
  "/../../src/headshots/Dance_RoyPark.webp",
  "/../../src/headshots/Dance_KyliHilaire.webp",
  "/../../src/headshots/Dance_ElvaJia.webp",
  "/../../src/headshots/Dance_AnnikaWu.webp",
  "/../../src/headshots/Dance_YikunYang.webp",
  "/../../src/headshots/Production_SowangKundeling.webp",
  "/../../src/headshots/Production_YeajooCho.webp",
  "/../../src/headshots/Production_VivianLiu.webp",
  "/../../src/headshots/Production_AliceYu.webp",
  "/../../src/headshots/Production_EshaShah.webp",
  "/../../src/headshots/Production_MaggieGuo.webp",
  "/../../src/headshots/Production_KarinaHalevy.webp",
  "/../../src/headshots/Production_JasperGitlitz.webp",
  "/../../src/headshots/Production_KatherineWang.webp",
  "/../../src/headshots/Production_FelixGabriel.webp",
  "/../../src/headshots/Production_HarrySchneider.webp",
  "/../../src/headshots/Production_NickBarreto.webp",
  "/../../src/headshots/Production_WillBerick.webp",
  "/../../src/headshots/Production_EricaFu.webp",
  "/../../src/headshots/Production_MaddieBurroughs.webp",
  "/../../src/headshots/Production_AidanHong.webp",
  "/../../src/headshots/Production_ChelseaTang.webp",
  "/../../src/headshots/Production_ErinChoi.webp",
  "/../../src/headshots/Production_KateLee.webp",
  "/../../src/headshots/Production_SusanNi.webp",
  "/../../src/headshots/Production_YukthaVemula.webp",
  "/../../src/headshots/Production_AsthaShah.webp",
  "/../../src/headshots/Production_LucyGunther.webp",
  "/../../src/headshots/Production_RiannaCampbell.webp",
  "/../../src/headshots/Production_EliseeaFaur.webp",
  "/../../src/headshots/Cinematography_RuiWang.webp",
  "/../../src/headshots/Cinematography_PeiranGe.webp",
  "/../../src/headshots/Cinematography_JenniferZhou.webp",
  "/../../src/headshots/Cinematography_MinjinBatzorig.webp",
  "/../../src/headshots/Hair_Makeup_TippiLi.webp",
  "/../../src/headshots/Hair_Makeup_AnnieWoo.webp",
  "/../../src/headshots/Hair_Makeup_DaniPreston.webp",
  "/../../src/headshots/Hair_Makeup_LaylaMalhas.webp",
  "/../../src/headshots/Hair_Makeup_JessicaLai.webp",
  "/../../src/headshots/Hair_Makeup_GraceLiao.webp",
  "/../../src/headshots/Hair_Makeup_MairssaLee.webp",
  "/../../src/headshots/Hair_Makeup_SulliYatabe.webp",
  "/../../src/headshots/Hair_Makeup_SulliYatabe.webp",
];



// const Executive_AnitaCheng = React.lazy(() => import("/src/headshots/Executive_AnitaCheng.webp"));
import Executive_AnitaCheng from "/src/headshots/Executive_AnitaCheng.webp"
import Executive_EllaSanfilippo from "/src/headshots/Executive_EllaSanfilippo.webp"
import Design_AmyHu from "/src/headshots/Design_AmyHu.webp"
import Design_AmandaWen from "/src/headshots/Design_AmandaWen.webp"
import Design_JuliaKasper from "/src/headshots/Design_JuliaKasper.webp"
import Design_MichaelDiGiovanna from "/src/headshots/Design_MichaelDiGiovanna.webp"
import Design_SaeraKim from "/src/headshots/Design_SaeraKim.webp"
import Design_MinjooKim from "/src/headshots/Design_MinjooKim.webp"
import Design_NayanaBalusu from "/src/headshots/Design_NayanaBalusu.webp"
import Design_BrookeSchwartz from "/src/headshots/Design_BrookeSchwartz.webp"
import Design_GwenToll from "/src/headshots/Design_GwenToll.webp"
import Design_SueahKim from "/src/headshots/Design_SueahKim.webp"
import Design_LeaDeVylder from "/src/headshots/Design_LeaDeVylder.webp"
import Design_KatrinaDarms from "/src/headshots/Design_KatrinaDarms.webp"
import Design_SydneySun from "/src/headshots/Design_SydneySun.webp"
import Design_ClarineLee from "/src/headshots/Design_ClarineLee.webp"
import Design_AnikaBhagavatula from "/src/headshots/Design_AnikaBhagavatula.webp"
import Design_HazelFroling from "/src/headshots/Design_HazelFroling.webp"
import Design_GraceKolosek from "/src/headshots/Design_GraceKolosek.webp"
import Design_CelineMin from "/src/headshots/Design_CelineMin.webp"
import Design_MayaGalindo_Benson from "/src/headshots/Design_MayaGalindo Benson.webp"
import Design_NicoleHuang from "/src/headshots/Design_NicoleHuang.webp"
import Design_SukieWang from "/src/headshots/Design_SukieWang.webp"
import Design_JacksonUnderwood from "/src/headshots/Design_JacksonUnderwood.webp"
import Design_RayyaGracy from "/src/headshots/Design_RayyaGracy.webp"
import Design_GraanaKhan from "/src/headshots/Design_GraanaKhan.webp"
import Design_CamelliaWang from "/src/headshots/Design_CamelliaWang.webp"
import Design_LilyDu from "/src/headshots/Design_LilyDu.webp"
import Creative_ChristyZo from "/src/headshots/Creative_ChristyZo.webp"
import Creative_HeysuOh from "/src/headshots/Creative_HeysuOh.webp"
import Creative_SophiaHao from "/src/headshots/Creative_SophiaHao.webp"
import Creative_ShannonLee from "/src/headshots/Creative_ShannonLee.webp"
import Creative_SophieHeap from "/src/headshots/Creative_SophieHeap.webp"
import Creative_LeslieLin from "/src/headshots/Creative_LeslieLin.webp"
import Creative_YuerZhu from "/src/headshots/Creative_YuerZhu.webp"
import Creative_DionLewis from "/src/headshots/Creative_DionLewis.webp"
import Creative_MicheleHratko from "/src/headshots/Creative_MicheleHratko.webp"
import Creative_JoannaNi from "/src/headshots/Creative_JoannaNi.webp"
import Creative_PhoebeLee from "/src/headshots/Creative_PhoebeLee.webp"
import Creative_ShannonLin from "/src/headshots/Creative_ShannonLin.webp"
import Creative_JeffreyYe from "/src/headshots/Creative_JeffreyYe.webp"
import Creative_AarnavPatel from "/src/headshots/Creative_AarnavPatel.webp"
import Creative_JingPeng from "/src/headshots/Creative_JingPeng.webp"
import Creative_MasonWang from "/src/headshots/Creative_MasonWang.webp"
import Creative_SuannaZhong from "/src/headshots/Creative_SuannaZhong.webp"
import Creative_ErinHsu from "/src/headshots/Creative_ErinHsu.webp"
import Creative_EuniceLai from "/src/headshots/Creative_EuniceLai.webp"
import Creative_PerryChen from "/src/headshots/Creative_PerryChen.webp"
import Creative_OscarWang from "/src/headshots/Creative_OscarWang.webp"
import Creative_MatthewAkuamoah_Boateng from "/src/headshots/Creative_MatthewAkuamoah-Boateng.webp"
import Creative_NicholasBaek from "/src/headshots/Creative_NicholasBaek.webp"
import Creative_SherryChen from "/src/headshots/Creative_SherryChen.webp"
import Creative_YonMaor from "/src/headshots/Creative_YonMaor.webp"
import Creative_ChrisSong from "/src/headshots/Creative_ChrisSong.webp"
import Creative_StacyChen from "/src/headshots/Creative_StacyChen.webp"
import Creative_AydenXu from "/src/headshots/Creative_AydenXu.webp"
import Creative_ErvinSong from "/src/headshots/Creative_ErvinSong.webp"
import Creative_VivianaStaicu from "/src/headshots/Creative_VivianaStaicu.webp"
import Creative_EricLin from "/src/headshots/Creative_EricLin.webp"
import Creative_MinsungKang from "/src/headshots/Creative_MinsungKang.webp"
import Creative_AChair from "/src/headshots/Creative_AChair.webp"
import Model_JeffreyZhang from "/src/headshots/Model_JeffreyZhang.webp"
import Model_BrookeGunter from "/src/headshots/Model_BrookeGunter.webp"
import Model_AnnaGerchanovsky from "/src/headshots/Model_AnnaGerchanovsky.webp"
import Model_YaninaShavialenka from "/src/headshots/Model_YaninaShavialenka.webp"
import Model_AndrewZhou from "/src/headshots/Model_AndrewZhou.webp"
import Model_MarissaFernandez from "/src/headshots/Model_MarissaFernandez.webp"
import Model_TimothyKim from "/src/headshots/Model_TimothyKim.webp"
import Model_MayaOusachi from "/src/headshots/Model_MayaOusachi.webp"
import Model_ElizabethHager from "/src/headshots/Model_ElizabethHager.webp"
import Model_JoyLeung from "/src/headshots/Model_JoyLeung.webp"
import Model_KevinTong from "/src/headshots/Model_KevinTong.webp"
import Model_DunnZhang from "/src/headshots/Model_DunnZhang.webp"
import Model_DestiniBrown_Greene from "/src/headshots/Model_DestiniBrown-Greene.webp"
import Model_MildredAmofa from "/src/headshots/Model_MildredAmofa.webp"
import Model_LucyHwang from "/src/headshots/Model_LucyHwang.webp"
import Model_JocelynSu from "/src/headshots/Model_JocelynSu.webp"
import Model_CarolineLaPiana from "/src/headshots/Model_CarolineLaPiana.webp"
import Model_SallyPak from "/src/headshots/Model_SallyPak.webp"
import Model_DhrutiKuchibhotla from "/src/headshots/Model_DhrutiKuchibhotla.webp"
import Model_Olu_BankeBoakye_Yiadom from "/src/headshots/Model_Olu-BankeBoakye-Yiadom.webp"
import PR_LillianHao from "/src/headshots/PR_LillianHao.webp"
import PR_PeggyShen from "/src/headshots/PR_PeggyShen.webp"
import PR_AngelaHuang from "/src/headshots/PR_AngelaHuang.webp"
import PR_JiaxinLin from "/src/headshots/PR_JiaxinLin.webp"
import PR_JoelleLee from "/src/headshots/PR_JoelleLee.webp"
import PR_KirstenPark from "/src/headshots/PR_KirstenPark.webp"
import Dance_JisooHan from "/src/headshots/Dance_JisooHan.webp"
import Dance_VeraZhong from "/src/headshots/Dance_VeraZhong.webp"
import Dance_FranStedman from "/src/headshots/Dance_FranStedman.webp"
import Dance_AlisaLo from "/src/headshots/Dance_AlisaLo.webp"
import Dance_SaanikaChauk from "/src/headshots/Dance_SaanikaChauk.webp"
import Dance_KaitlynXie from "/src/headshots/Dance_KaitlynXie.webp"
import Dance_LiannaHuang from "/src/headshots/Dance_LiannaHuang.webp"
import Dance_ChaseGumbs from "/src/headshots/Dance_ChaseGumbs.webp"
import Dance_AJSeo from "/src/headshots/Dance_AJSeo.webp"
import Dance_HelenHuang from "/src/headshots/Dance_HelenHuang.webp"
import Dance_KellyDam from "/src/headshots/Dance_KellyDam.webp"
import Dance_YujunWu from "/src/headshots/Dance_YujunWu.webp"
import Dance_CindyLiu from "/src/headshots/Dance_CindyLiu.webp"
import Dance_JoannaGe from "/src/headshots/Dance_JoannaGe.webp"
import Dance_SmritiChopra from "/src/headshots/Dance_SmritiChopra.webp"
import Dance_HannaLuo from "/src/headshots/Dance_HannaLuo.webp"
import Dance_AnnikaWu from "/src/headshots/Dance_AnnikaWu.webp"
import Dance_AliceAnie from "/src/headshots/Dance_AliceAnie.webp"
import Dance_KateLee from "/src/headshots/Dance_KateLee.webp"
import Dance_SharonRen from "/src/headshots/Dance_SharonRen.webp"
import Dance_SophiaHoch from "/src/headshots/Dance_SophiaHoch.webp"
import Dance_CarolineMichalow from "/src/headshots/Dance_CarolineMichalow.webp"
import Dance_YuXiLee from "/src/headshots/Creative_AChair.webp" // "/src/headshots/Dance_YuXiLee.webp" DOESN'T WORK
import Dance_LaurenLoriaSklar from "/src/headshots/Dance_LaurenLoriaSklar.webp"
import Dance_SamanthaVu from "/src/headshots/Dance_SamanthaVu.webp"
import Dance_IancaDeLosSantos from "/src/headshots/Dance_IancaDeLosSantos.webp"
import Dance_LilyStern from "/src/headshots/Dance_LilyStern.webp"
import Dance_VeraMazeeva from "/src/headshots/Dance_VeraMazeeva.webp"
import Dance_AudreyShao from "/src/headshots/Dance_AudreyShao.webp"
import Dance_BrooklynMao from "/src/headshots/Dance_BrooklynMao.webp"
import Dance_RebeccaJiang from "/src/headshots/Dance_RebeccaJiang.webp"
import Dance_RoyPark from "/src/headshots/Dance_RoyPark.webp"
import Dance_KyliHilaire from "/src/headshots/Dance_KyliHilaire.webp"
import Dance_ElvaJia from "/src/headshots/Dance_ElvaJia.webp"
import Dance_YikunYang from "/src/headshots/Dance_YikunYang.webp"
import Production_SowangKundeling from "/src/headshots/Production_SowangKundeling.webp"
import Production_YeajooCho from "/src/headshots/Production_YeajooCho.webp"
import Production_VivianLiu from "/src/headshots/Production_VivianLiu.webp"
import Production_AliceYu from "/src/headshots/Production_AliceYu.webp"
import Production_EshaShah from "/src/headshots/Production_EshaShah.webp"
import Production_MaggieGuo from "/src/headshots/Production_MaggieGuo.webp"
import Production_KarinaHalevy from "/src/headshots/Production_KarinaHalevy.webp"
import Production_JasperGitlitz from "/src/headshots/Production_JasperGitlitz.webp"
import Production_KatherineWang from "/src/headshots/Production_KatherineWang.webp"
import Production_FelixGabriel from "/src/headshots/Production_FelixGabriel.webp"
import Production_HarrySchneider from "/src/headshots/Production_HarrySchneider.webp"
import Production_NickBarreto from "/src/headshots/Production_NickBarreto.webp"
import Production_WillBerick from "/src/headshots/Production_WillBerick.webp"
import Production_EricaFu from "/src/headshots/Production_EricaFu.webp"
import Production_MaddieBurroughs from "/src/headshots/Production_MaddieBurroughs.webp"
import Production_AidanHong from "/src/headshots/Production_AidanHong.webp"
import Production_ChelseaTang from "/src/headshots/Production_ChelseaTang.webp"
import Production_ErinChoi from "/src/headshots/Production_ErinChoi.webp"
import Production_KateLee from "/src/headshots/Production_KateLee.webp"
import Production_SusanNi from "/src/headshots/Production_SusanNi.webp"
import Production_YukthaVemula from "/src/headshots/Production_YukthaVemula.webp"
import Production_AsthaShah from "/src/headshots/Production_AsthaShah.webp"
import Production_LucyGunther from "/src/headshots/Production_LucyGunther.webp"
import Production_RiannaCampbell from "/src/headshots/Production_RiannaCampbell.webp"
import Production_EliseeaFaur from "/src/headshots/Production_EliseeaFaur.webp"
import Cinematography_RuiWang from "/src/headshots/Cinematography_RuiWang.webp"
import Cinematography_PeiranGe from "/src/headshots/Cinematography_PeiranGe.webp"
import Cinematography_JenniferZhou from "/src/headshots/Cinematography_JenniferZhou.webp"
import Cinematography_MinjinBatzorig from "/src/headshots/Cinematography_MinjinBatzorig.webp"
import Hair_Makeup_TippiLi from "/src/headshots/Hair_Makeup_TippiLi.webp"
import Hair_Makeup_AnnieWoo from "/src/headshots/Hair_Makeup_AnnieWoo.webp"
import Hair_Makeup_DaniPreston from "/src/headshots/Hair_Makeup_DaniPreston.webp"
import Hair_Makeup_LaylaMalhas from "/src/headshots/Hair_Makeup_LaylaMalhas.webp"
import Hair_Makeup_JessicaLai from "/src/headshots/Hair_Makeup_JessicaLai.webp"
import Hair_Makeup_GraceLiao from "/src/headshots/Hair_Makeup_GraceLiao.webp"
import Hair_Makeup_MairssaLee from "/src/headshots/Hair_Makeup_MairssaLee.webp"
import Hair_Makeup_SulliYatabe from "/src/headshots/Hair_Makeup_SulliYatabe.webp"

export const images = [
  Executive_AnitaCheng, 
  Executive_EllaSanfilippo, 
  Design_AmyHu, 
  Design_AmandaWen, 
  Design_JuliaKasper, 
  Design_MichaelDiGiovanna, 
  Design_SaeraKim, 
  Design_MinjooKim, 
  Design_NayanaBalusu, 
  Design_BrookeSchwartz, 
  Design_GwenToll, 
  Design_SueahKim, 
  Design_LeaDeVylder, 
  Design_KatrinaDarms, 
  Design_SydneySun, 
  Design_ClarineLee, 
  Design_AnikaBhagavatula, 
  Design_HazelFroling, 
  Design_GraceKolosek, 
  Design_CelineMin, 
  Design_MayaGalindo_Benson, 
  Design_NicoleHuang, 
  Design_SukieWang, 
  Design_JacksonUnderwood, 
  Design_RayyaGracy, 
  Design_GraanaKhan, 
  Design_CamelliaWang, 
  Design_LilyDu, 
  Creative_ChristyZo, 
  Creative_HeysuOh, 
  Creative_SophiaHao, 
  Creative_ShannonLee, 
  Creative_SophieHeap, 
  Creative_LeslieLin, 
  Creative_YuerZhu, 
  Creative_DionLewis, 
  Creative_MicheleHratko, 
  Creative_JoannaNi, 
  Creative_PhoebeLee, 
  Creative_ShannonLin, 
  Creative_JeffreyYe, 
  Creative_AarnavPatel, 
  Creative_JingPeng, 
  Creative_MasonWang, 
  Creative_SuannaZhong, 
  Creative_ErinHsu, 
  Creative_EuniceLai, 
  Creative_PerryChen, 
  Creative_OscarWang, 
  Creative_MatthewAkuamoah_Boateng, 
  Creative_NicholasBaek, 
  Creative_SherryChen, 
  Creative_YonMaor, 
  Creative_ChrisSong, 
  Creative_StacyChen, 
  Creative_AydenXu, 
  Creative_ErvinSong, 
  Creative_VivianaStaicu, 
  Creative_EricLin, 
  Creative_MinsungKang, 
  Creative_AChair, 
  Model_JeffreyZhang, 
  Model_BrookeGunter, 
  Model_AnnaGerchanovsky, 
  Model_YaninaShavialenka, 
  Model_AndrewZhou, 
  Model_MarissaFernandez, 
  Model_TimothyKim, 
  Model_MayaOusachi, 
  Model_ElizabethHager, 
  Model_JoyLeung, 
  Model_KevinTong, 
  Model_DunnZhang, 
  Model_DestiniBrown_Greene, 
  Model_MildredAmofa, 
  Model_LucyHwang, 
  Model_JocelynSu, 
  Model_CarolineLaPiana, 
  Model_SallyPak, 
  Model_DhrutiKuchibhotla, 
  Model_Olu_BankeBoakye_Yiadom, 
  PR_LillianHao, 
  PR_PeggyShen, 
  PR_AngelaHuang, 
  PR_JiaxinLin, 
  PR_JoelleLee, 
  PR_KirstenPark, 
  Dance_JisooHan, 
  Dance_VeraZhong, 
  Dance_FranStedman, 
  Dance_AlisaLo, 
  Dance_SaanikaChauk, 
  Dance_KaitlynXie, 
  Dance_LiannaHuang, 
  Dance_ChaseGumbs, 
  Dance_AJSeo, 
  Dance_HelenHuang, 
  Dance_KellyDam, 
  Dance_YujunWu, 
  Dance_CindyLiu, 
  Dance_JoannaGe, 
  Dance_FranStedman, 
  Dance_SmritiChopra, 
  Dance_HannaLuo, 
  Dance_AnnikaWu, 
  Dance_AliceAnie, 
  Dance_KateLee, 
  Dance_SharonRen, 
  Dance_SophiaHoch, 
  Dance_CarolineMichalow, 
  Dance_YuXiLee, 
  Dance_LaurenLoriaSklar, 
  Dance_SamanthaVu, 
  Dance_IancaDeLosSantos, 
  Dance_LilyStern, 
  Dance_VeraMazeeva, 
  Dance_AudreyShao, 
  Dance_BrooklynMao, 
  Dance_RebeccaJiang, 
  Dance_RoyPark, 
  Dance_KyliHilaire, 
  Dance_ElvaJia, 
  Dance_AnnikaWu, 
  Dance_YikunYang, 
  Production_SowangKundeling, 
  Production_YeajooCho, 
  Production_VivianLiu, 
  Production_AliceYu, 
  Production_EshaShah, 
  Production_MaggieGuo, 
  Production_KarinaHalevy, 
  Production_JasperGitlitz, 
  Production_KatherineWang, 
  Production_FelixGabriel, 
  Production_HarrySchneider, 
  Production_NickBarreto, 
  Production_WillBerick, 
  Production_EricaFu, 
  Production_MaddieBurroughs, 
  Production_AidanHong, 
  Production_ChelseaTang, 
  Production_ErinChoi, 
  Production_KateLee, 
  Production_SusanNi, 
  Production_YukthaVemula, 
  Production_AsthaShah, 
  Production_LucyGunther, 
  Production_RiannaCampbell, 
  Production_EliseeaFaur, 
  Cinematography_RuiWang, 
  Cinematography_PeiranGe, 
  Cinematography_JenniferZhou, 
  Cinematography_MinjinBatzorig, 
  Hair_Makeup_TippiLi, 
  Hair_Makeup_AnnieWoo, 
  Hair_Makeup_DaniPreston, 
  Hair_Makeup_LaylaMalhas, 
  Hair_Makeup_JessicaLai, 
  Hair_Makeup_GraceLiao, 
  Hair_Makeup_MairssaLee, 
  Hair_Makeup_SulliYatabe, 
  Hair_Makeup_SulliYatabe, 
]