export const names = [
  "Anita Cheng",
  "Ella Sanfilippo",
  "Amy Hu",
  "Amanda Wen",
  "Julia Kasper",
  "Michael DiGiovanna",
  "Saera Kim",
  "Minjoo Kim",
  "Nayana Balusu",
  "Brooke Schwartz",
  "Gwen Toll",
  "Sueah Kim",
  "Lea DeVylder",
  "Katrina Darms",
  "Sydney Sun",
  "Clarine Lee",
  "Anika Bhagavatula",
  "Hazel Froling",
  "Grace Kolosek",
  "Celine Min",
  "Maya Galindo Benson",
  "Nicole Huang",
  "Sukie Wang",
  "Jackson Underwood",
  "Rayya Gracy",
  "Graana Khan",
  "Camellia Wang",
  "Lily Du",
  "Christy Zo",
  "Heysu Oh",
  "Sophia Hao",
  "Shannon Lee",
  "Sophie Heap",
  "Leslie Lin",
  "Yuer Zhu",
  "Dion Lewis",
  "Michele Hratko",
  "Joanna Ni",
  "Phoebe Lee",
  "Shannon Lin",
  "Jeffrey Ye",
  "Aarnav Patel",
  "Jing Peng",
  "A Chair",
  "Suanna Zhong",
  "Erin Hsu",
  "Eunice Lai",
  "Perry Chen",
  "Oscar Wang",
  "Matthew Akuamoah-Boateng",
  "Nicholas Baek",
  "Sherry Chen",
  "Yon Maor",
  "Chris Song",
  "Stacy Chen",
  "Ayden Xu",
  "Ervin Song",
  "Viviana Staicu",
  "Eric Lin",
  "Minsung Kang",
  "A Chair",
  "Jeffrey Zhang",
  "Brooke Gunter",
  "Anna Gerchanovsky",
  "Yanina Shavialenka",
  "Andrew Zhou",
  "Marissa Fernandez",
  "Timothy Kim",
  "Maya Ousachi",
  "Elizabeth Hager",
  "Joy Leung",
  "Kevin Tong",
  "Dunn Zhang",
  "Destini Brown-Greene",
  "Mildred Amofa",
  "Lucy Hwang",
  "Jocelyn Su",
  "Caroline LaPiana",
  "Sally Pak",
  "Dhruti Kuchibhotla",
  "Olu-Banke Boakye-Yiadom",
  "Lillian Hao",
  "Peggy Shen",
  "Angela Huang",
  "Jiaxin Lin",
  "Joelle Lee",
  "Kirsten Park",
  "Jisoo Han",
  "Vera Zhong",
  "Fran Stedman",
  "Alisa Lo",
  "Saanika Chauk",
  "Kaitlyn Xie",
  "Lianna Huang",
  "Chase Gumbs",
  "AJ Seo",
  "Helen Huang",
  "Kelly Dam",
  "Yujun Wu",
  "Cindy Liu",
  "Joanna Ge",
  "Fran Stedman",
  "Smriti Chopra",
  "Hanna Luo",
  "Annika Wu",
  "Alice Anie",
  "Kate Lee",
  "Sharon Ren",
  "Sophia Hoch",
  "Caroline Michalow",
  "YuXi Lee",
  "Lauren LoriaSklar",
  "Samantha Vu",
  "Ianca DeLosSantos",
  "Lily Stern",
  "Vera Mazeeva",
  "Audrey Shao",
  "Brooklyn Mao",
  "Rebecca Jiang",
  "Roy Park",
  "Kyli Hilaire",
  "Elva Jia",
  "Annika Wu",
  "Yikun Yang",
  "Sowang Kundeling",
  "Yeajoo Cho",
  "Vivian Liu",
  "Alice Yu",
  "Esha Shah",
  "Maggie Guo",
  "Karina Halevy",
  "Jasper Gitlitz",
  "Katherine Wang",
  "Felix Gabriel",
  "Harry Schneider",
  "Nick Barreto",
  "Will Berick",
  "Erica Fu",
  "Maddie Burroughs",
  "Aidan Hong",
  "Chelsea Tang",
  "Erin Choi",
  "Kate Lee",
  "Susan Ni",
  "Yuktha Vemula",
  "Astha Shah",
  "Lucy Gunther",
  "Rianna Campbell",
  "Eliseea Faur",
  "Rui Wang",
  "Peiran Ge",
  "Jennifer Zhou",
  "Minjin Batzorig",
  "Tippi Li",
  "Annie Woo",
  "Dani Preston",
  "Layla Malhas",
  "Jessica Lai",
  "Grace Liao",
  "Mairssa Lee",
  "Sulli Yatabe",
  "Sulli Yatabe",
];
export const team = [
  "Co-Producer + Model",
  "Co-Producer",
  "Head of Design",
  "Design Coordinator",
  "Designer + Coordinator",
  "Designer + Coordinator",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer and PR",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Co-Head of Creative",
  "Co-Head of Creative",
  "Co-Head of Print",
  "Co-Head of Print",
  "Print member",
  "Print member + Dance",
  "Print member",
  "Print member",
  "print member",
  "Motion Member",
  "Head of Motion",
  "Motion Member",
  "Motion Member",
  "Motion Member",
  "Motion Member",
  "Chair",
  "Head of Photo",
  "Photo Member",
  "Photo Member",
  "Photo Member",
  "Photo Member",
  "Photo Member",
  "Photo Member",
  "Photo Member",
  "Head of Web :)",
  "Web Team :)",
  "Web Team :)",
  "Web Team :)",
  "Web Team :)",
  "Web Tea :)",
  "Web Team :)",
  "Web Team :)",
  "Chair",
  "Co-Head of Model",
  "Co-Head of Model",
  "Model Coordinator",
  "Model",
  "Model + Finance Assistant",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Head of Public Relations",
  "Co-Head of Digital Marketing",
  "Co-Head of Digital Marketing",
  "Digital Marketing Member",
  "Sponsorships Team Member",
  "Sponsorships Team Member",
  "Head of Dance",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dance Assistant",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "dancer",
  "Dancer",
  "Dancer",
  "",
  "",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Co-Head of Production",
  "Co-Head of Production",
  "Head of Box Office",
  "Box Office Coordinator",
  "Box Office Coordinator",
  "Box Office Coordinator",
  "Lighting Designer + \n Dancer",
  "Lighting Designer, \n SM Support",
  "Head of Sound Design + \n Model",
  "Sound Designer",
  "Sound Designer",
  "Sound Designer",
  "Sound Designer",
  "Co-Head of Stage Design + \n Hair/Makeup",
  "Co-Head of Stage Design",
  "Stage Designer",
  "Stage Designer",
  "Stage Designer",
  "Stage Designer",
  "Stage Designer",
  "Stage Designer",
  "Stage Manager",
  "Stage Manager",
  "Stage Manager",
  "Lighting Designer",
  "Co-Head of Cinematography",
  "Co-Head of Cinematography",
  "Cinematographer",
  "Cinematographer",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
];
export const title = [
  "Executive",
  "Executive",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "PR",
  "PR",
  "PR",
  "PR",
  "PR",
  "PR",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Cinematography",
  "Cinematography",
  "Cinematography",
  "Cinematography",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
];
export const urls = [
  "/headshots/Executive_AnitaCheng.jpg",
  "/headshots/Executive_EllaSanfilippo.jpg",
  "/headshots/Design_AmyHu.png",
  "/headshots/Design_AmandaWen.png",
  "/headshots/Design_JuliaKasper.png",
  "/headshots/Design_MichaelDiGiovanna.png",
  "/headshots/Design_SaeraKim.png",
  "/headshots/Design_MinjooKim.png",
  "/headshots/Design_NayanaBalusu.png",
  "/headshots/Design_BrookeSchwartz.png",
  "/headshots/Design_GwenToll.png",
  "/headshots/Design_SueahKim.png",
  "/headshots/Design_LeaDeVylder.png",
  "/headshots/Design_KatrinaDarms.png",
  "/headshots/Design_SydneySun.png",
  "/headshots/Design_ClarineLee.png",
  "/headshots/Design_AnikaBhagavatula.png",
  "/headshots/Design_HazelFroling.png",
  "/headshots/Design_GraceKolosek.png",
  "/headshots/Design_CelineMin.png",
  "/headshots/Design_MayaGalindo Benson.png",
  "/headshots/Design_NicoleHuang.png",
  "/headshots/Design_SukieWang.png",
  "/headshots/Design_JacksonUnderwood.png",
  "/headshots/Design_RayyaGracy.png",
  "/headshots/Design_GraanaKhan.png",
  "/headshots/Design_CamelliaWang.png",
  "/headshots/Design_LilyDu.png",
  "/headshots/Creative_ChristyZo.jpg",
  "/headshots/Creative_HeysuOh.jpg",
  "/headshots/Creative_SophiaHao.jpg",
  "/headshots/Creative_ShannonLee.jpg",
  "/headshots/Creative_SophieHeap.jpg",
  "/headshots/Creative_LeslieLin.jpg",
  "/headshots/Creative_YuerZhu.jpg",
  "/headshots/Creative_DionLewis.jpg",
  "/headshots/Creative_MicheleHratko.jpg",
  "/headshots/Creative_JoannaNi.jpg",
  "/headshots/Creative_PhoebeLee.jpg",
  "/headshots/Creative_ShannonLin.jpg",
  "/headshots/Creative_JeffreyYe.jpg",
  "/headshots/Creative_AarnavPatel.jpg",
  "/headshots/Creative_JingPeng.jpg",
  "/headshots/Creative_AChair.jpg",
  "/headshots/Creative_SuannaZhong.jpg",
  "/headshots/Creative_ErinHsu.jpg",
  "/headshots/Creative_EuniceLai.jpg",
  "/headshots/Creative_PerryChen.jpg",
  "/headshots/Creative_OscarWang.jpg",
  "/headshots/Creative_MatthewAkuamoah-Boateng.jpg",
  "/headshots/Creative_NicholasBaek.jpg",
  "/headshots/Creative_SherryChen.jpg",
  "/headshots/Creative_YonMaor.jpg",
  "/headshots/Creative_ChrisSong.jpg",
  "/headshots/Creative_StacyChen.jpg",
  "/headshots/Creative_AydenXu.jpg",
  "/headshots/Creative_ErvinSong.jpg",
  "/headshots/Creative_VivianaStaicu.jpg",
  "/headshots/Creative_EricLin.jpg",
  "/headshots/Creative_MinsungKang.jpg",
  "/headshots/Creative_AChair.jpg",
  "/headshots/Model_JeffreyZhang.jpg",
  "/headshots/Model_BrookeGunter.jpg",
  "/headshots/Model_AnnaGerchanovsky.jpg",
  "/headshots/Model_YaninaShavialenka.jpg",
  "/headshots/Model_AndrewZhou.jpg",
  "/headshots/Model_MarissaFernandez.jpg",
  "/headshots/Model_TimothyKim.jpg",
  "/headshots/Model_MayaOusachi.jpg",
  "/headshots/Model_ElizabethHager.jpg",
  "/headshots/Model_JoyLeung.jpg",
  "/headshots/Model_KevinTong.jpg",
  "/headshots/Model_DunnZhang.jpg",
  "/headshots/Model_DestiniBrown-Greene.jpg",
  "/headshots/Model_MildredAmofa.jpg",
  "/headshots/Model_LucyHwang.jpg",
  "/headshots/Model_JocelynSu.jpg",
  "/headshots/Model_CarolineLaPiana.jpg",
  "/headshots/Model_SallyPak.jpg",
  "/headshots/Model_DhrutiKuchibhotla.jpg",
  "/headshots/Model_Olu-BankeBoakye-Yiadom.jpg",
  "/headshots/PR_LillianHao.jpg",
  "/headshots/PR_PeggyShen.jpg",
  "/headshots/PR_AngelaHuang.jpg",
  "/headshots/PR_JiaxinLin.jpg",
  "/headshots/PR_JoelleLee.jpg",
  "/headshots/PR_KirstenPark.jpg",
  "/headshots/Dance_JisooHan.jpg",
  "/headshots/Dance_VeraZhong.jpg",
  "/headshots/Dance_FranStedman.jpg",
  "/headshots/Dance_AlisaLo.jpg",
  "/headshots/Dance_SaanikaChauk.jpg",
  "/headshots/Dance_KaitlynXie.jpg",
  "/headshots/Dance_LiannaHuang.jpg",
  "/headshots/Dance_ChaseGumbs.jpg",
  "/headshots/Dance_AJSeo.jpg",
  "/headshots/Dance_HelenHuang.jpg",
  "/headshots/Dance_KellyDam.jpg",
  "/headshots/Dance_YujunWu.jpg",
  "/headshots/Dance_CindyLiu.jpg",
  "/headshots/Dance_JoannaGe.jpg",
  "/headshots/Dance_FranStedman.jpg",
  "/headshots/Dance_SmritiChopra.jpg",
  "/headshots/Dance_HannaLuo.jpg",
  "/headshots/Dance_AnnikaWu.jpg",
  "/headshots/Dance_AliceAnie.jpg",
  "/headshots/Dance_KateLee.jpg",
  "/headshots/Dance_SharonRen.jpg",
  "/headshots/Dance_SophiaHoch.jpg",
  "/headshots/Dance_CarolineMichalow.jpg",
  "/headshots/Dance_YuXiLee.jpg",
  "/headshots/Dance_LaurenLoriaSklar.jpg",
  "/headshots/Dance_SamanthaVu.jpg",
  "/headshots/Dance_IancaDeLosSantos.jpg",
  "/headshots/Dance_LilyStern.jpg",
  "/headshots/Dance_VeraMazeeva.jpg",
  "/headshots/Dance_AudreyShao.jpg",
  "/headshots/Dance_BrooklynMao.jpg",
  "/headshots/Dance_RebeccaJiang.jpg",
  "/headshots/Dance_RoyPark.jpg",
  "/headshots/Dance_KyliHilaire.jpg",
  "/headshots/Dance_ElvaJia.jpg",
  "/headshots/Dance_AnnikaWu.jpg",
  "/headshots/Dance_YikunYang.jpg",
  "/headshots/Production_SowangKundeling.jpg",
  "/headshots/Production_YeajooCho.jpg",
  "/headshots/Production_VivianLiu.jpg",
  "/headshots/Production_AliceYu.jpg",
  "/headshots/Production_EshaShah.jpg",
  "/headshots/Production_MaggieGuo.jpg",
  "/headshots/Production_KarinaHalevy.jpg",
  "/headshots/Production_JasperGitlitz.jpg",
  "/headshots/Production_KatherineWang.jpg",
  "/headshots/Production_FelixGabriel.jpg",
  "/headshots/Production_HarrySchneider.jpg",
  "/headshots/Production_NickBarreto.jpg",
  "/headshots/Production_WillBerick.jpg",
  "/headshots/Production_EricaFu.jpg",
  "/headshots/Production_MaddieBurroughs.jpg",
  "/headshots/Production_AidanHong.jpg",
  "/headshots/Production_ChelseaTang.jpg",
  "/headshots/Production_ErinChoi.jpg",
  "/headshots/Production_KateLee.jpg",
  "/headshots/Production_SusanNi.jpg",
  "/headshots/Production_YukthaVemula.jpg",
  "/headshots/Production_AsthaShah.jpg",
  "/headshots/Production_LucyGunther.jpg",
  "/headshots/Production_RiannaCampbell.jpg",
  "/headshots/Production_EliseeaFaur.jpg",
  "/headshots/Cinematography_RuiWang.jpg",
  "/headshots/Cinematography_PeiranGe.jpg",
  "/headshots/Cinematography_JenniferZhou.jpg",
  "/headshots/Cinematography_MinjinBatzorig.jpg",
  "/headshots/Hair_Makeup_TippiLi.jpeg",
  "/headshots/Hair_Makeup_AnnieWoo.jpeg",
  "/headshots/Hair_Makeup_DaniPreston.jpeg",
  "/headshots/Hair_Makeup_LaylaMalhas.jpeg",
  "/headshots/Hair_Makeup_JessicaLai.jpeg",
  "/headshots/Hair_Makeup_GraceLiao.jpeg",
  "/headshots/Hair_Makeup_MairssaLee.jpeg",
  "/headshots/Hair_Makeup_SulliYatabe.jpeg",
  "/headshots/Hair_Makeup_SulliYatabe.jpeg",
];
