export const names = [
  "Anita Cheng",
  "Ella Sanfilippo",
  "Sowang Kundeling",
  "Yeajoo Cho",
  "Vivian Liu",
  "Alice Yu",
  "Esha Shah",
  "Maggie Guo",
  "Karina Halevy",
  "Jasper Gitlitz",
  "Katherine Wang",
  "FelixGabriel Ureña",
  "Harry Schneider",
  "Nick Barreto",
  "Will Berick",
  "Erica Fu",
  "Maddie Burroughs",
  "Aidan Hong",
  "Chelsea Tang",
  "Erin Choi",
  "Kate Lee",
  "Susan Ni",
  "Yuktha Vemula",
  "Astha Shah",
  "Lucy Gunther",
  "Rianna Campbell",
  "Eliseea Faur",
  "Rui Wang",
  "Peiran Ge",
  "Minjin Batzorig",
  "Christy Zo",
  "Heysu Oh",
  "Sophia Hao",
  "Shannon Lee",
  "Sophie Heap",
  "Leslie Lin",
  "Yuer Zhu",
  "Dion Lewis",
  "Michele Hratko",
  "Joanna Ni",
  "Phoebe Lee",
  "Shannon Lin",
  "Jeffrey Ye",
  "Aarnav Patel",
  "Jing Peng",
  "Mason Wang",
  "Suanna Zhong",
  "Erin Hsu",
  "Eunice Lai",
  "Perry Chen",
  "Oscar Wang",
  "Matthew Akuamoah-Boateng",
  "Nicholas Baek",
  "Sherry Chen",
  "Yon Maor",
  "Chris Song",
  "Stacy Chen",
  "Ayden Xu",
  "Ervin Song",
  "Viviana Staicu",
  "Eric Lin",
  "Minsung Kang",
  "Lillian Hao",
  "Peggy Shen",
  "Angela Huang",
  "Jiaxin Lin",
  "Joelle Lee",
  "Kirsten Park",
  "Amy Hu",
  "Amanda Wen",
  "Julia Kasper",
  "Michael DiGiovanna",
  "Saera Kim",
  "Minjoo Kim",
  "Nayana Balusu",
  "Brooke Schwartz",
  "Gwen Toll",
  "Sueah Kim",
  "Lea DeVylder",
  "Katrina Darms",
  "Sydney Sun",
  "Clarine Lee",
  "Anika Bhagavatula",
  "Hazel Froling",
  "Grace Kolosek",
  "Celine Min",
  "Maya Galindo Benson",
  "Nicole Huang",
  "Sukie Wang",
  "Jackson Underwood",
  "Rayya Gracy",
  "Graana Khan",
  "Camellia Wang",
  "Lily Du",
  "Jeffrey Zhang",
  "Brooke Gunter",
  "Anna Gerchanovsky",
  "Yanina Shavialenka",
  "Andrew Zhou",
  "Marissa Fernandez",
  "Timothy Kim",
  "Maya Ousachi",
  "Elizabeth Hager",
  "Joy Leung",
  "Kevin Tong",
  "Dunn Zhang",
  "Destini Brown-Greene",
  "Mildred Amofa",
  "Lucy Hwang",
  "Jocelyn Su",
  "Caroline LaPiana",
  "Sally Pak",
  "Dhruti Kuchibhotla",
  "Olu-Banke Boakye-Yiadom",
  "Tippi Li",
  "Annie Woo",
  "Dani Preston",
  "Layla Malhas",
  "Jessica Lai",
  "Grace Liao",
  "Mairssa Lee",
  "Sulli Yatabe",
  "Jisoo Han",
  "Vera Zhong",
  "Fran Stedman",
  "Alisa Lo",
  "Saanika Chauk",
  "Kaitlyn Xie",
  "Lianna Huang",
  "Chase Gumbs",
  "AJ Seo",
  "Helen Huang",
  "Kelly Dam",
  "Yujun Wu",
  "Cindy Liu",
  "Joanna Ge",
  "Fran Stedman",
  "Smriti Chopra",
  "Hanna Luo",
  "Annika Wu",
  "Alice Anie",
  "Kate Lee",
  "Sharon Ren",
  "Sophia Hoch",
  "Caroline Michalow",
  "YuXi Lee",
  "Lauren LoriaSklar",
  "Samantha Vu",
  "Ianca DeLosSantos",
  "Lily Stern",
  "Vera Mazeeva",
  "Audrey Shao",
  "Brooklyn Mao",
  "Rebecca Jiang",
  "Roy Park",
  "Kyli Hilaire",
  "Elva Jia",
  "Annika Wu",
  "Yikun Yang",
];
export const team = [
  "Co-Producer + Model",
  "Co-Producer",
  "Co-Head of Production",
  "Co-Head of Production",
  "Head of Box Office",
  "Box Office Coordinator",
  "Box Office Coordinator",
  "Box Office Coordinator",
  "Lighting Designer + Dancer",
  "Lighting Designer, SM Support",
  "Head of Sound Design + \n Model",
  "Sound Designer",
  "Sound Designer",
  "Sound Designer",
  "Sound Designer",
  "Co-Head of Stage Design + \n Hair/Makeup",
  "Co-Head of Stage Design",
  "Stage Designer",
  "Stage Designer",
  "Stage Designer",
  "Stage Designer",
  "Stage Designer",
  "Stage Designer",
  "Stage Manager",
  "Stage Manager",
  "Stage Manager",
  "Lighting Designer",
  "Co-Head of Cinematography",
  "Co-Head of Cinematography",
  "Cinematographer",
  "Co-Head of Creative",
  "Co-Head of Creative",
  "Co-Head of Print",
  "Co-Head of Print",
  "Print member",
  "Print member + Dance",
  "Print member",
  "Print member",
  "print member",
  "motion member",
  "Head of Motion",
  "motion member",
  "motion member",
  "motion member",
  "motion member",
  "motion member",
  "Head of Photo",
  "photo member",
  "photo member",
  "Photo member",
  "photo member",
  "photo member",
  "photo member",
  "photo member",
  "Head of weeb",
  "weeb",
  "weeb",
  "weeb",
  "weeb",
  "weeb",
  "weeb",
  "weeb",
  "Head of Public Relations",
  "Co-Head of Digital Marketing",
  "Co-Head of Digital Marketing",
  "Member of Digital Marketing Team",
  "Member of Sponsorships Team",
  "Member of Sponsorships Team",
  "Head of Design",
  "Design Coordinator",
  "Design Coordinator, Designer",
  "Design Coordinator, Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer and PR",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Designer",
  "Co-Head of Model",
  "Co-Head of Model",
  "Model Coordinator",
  "Model",
  "Model + Finance Assistant",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Head of Dance",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dance Assistant",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "dancer",
  "Dancer",
  "Dancer",
  "",
  "",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
  "Dancer",
];
export const title = [
  "Executive",
  "Executive",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Production",
  "Cinematography",
  "Cinematography",
  "Cinematography",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "Creative",
  "PR",
  "PR",
  "PR",
  "PR",
  "PR",
  "PR",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Design",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Model",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Hair/Makeup",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
  "Dance",
];
export const urls = [
  "people/src/assets/headshots/Executive_AnitaCheng.jpg",
  "people/src/assets/headshots/Executive_EllaSanfilippo.jpg",
  "people/src/assets/headshots/Production_SowangKundeling.jpg",
  "people/src/assets/headshots/Production_YeajooCho.jpg",
  "people/src/assets/headshots/Production_VivianLiu.jpg",
  "people/src/assets/headshots/Production_AliceYu.jpg",
  "people/src/assets/headshots/Production_EshaShah.jpg",
  "people/src/assets/headshots/Production_MaggieGuo.jpg",
  "people/src/assets/headshots/Production_KarinaHalevy.jpg",
  "people/src/assets/headshots/Production_JasperGitlitz.jpg",
  "people/src/assets/headshots/Production_KatherineWang.jpg",
  "people/src/assets/headshots/Production_FelixGabrielUreña.jpg",
  "people/src/assets/headshots/Production_HarrySchneider.jpg",
  "people/src/assets/headshots/Production_NickBarreto.jpg",
  "people/src/assets/headshots/Production_WillBerick.jpg",
  "people/src/assets/headshots/Production_EricaFu.jpg",
  "people/src/assets/headshots/Production_MaddieBurroughs.jpg",
  "people/src/assets/headshots/Production_AidanHong.jpg",
  "people/src/assets/headshots/Production_ChelseaTang.jpg",
  "people/src/assets/headshots/Production_ErinChoi.jpg",
  "people/src/assets/headshots/Production_KateLee.jpg",
  "people/src/assets/headshots/Production_SusanNi.jpg",
  "people/src/assets/headshots/Production_YukthaVemula.jpg",
  "people/src/assets/headshots/Production_AsthaShah.jpg",
  "people/src/assets/headshots/Production_LucyGunther.jpg",
  "people/src/assets/headshots/Production_RiannaCampbell.jpg",
  "people/src/assets/headshots/Production_EliseeaFaur.jpg",
  "people/src/assets/headshots/Cinematography_RuiWang.jpg",
  "people/src/assets/headshots/Cinematography_PeiranGe.jpg",
  "people/src/assets/headshots/Cinematography_MinjinBatzorig.jpg",
  "people/src/assets/headshots/Creative_ChristyZo.jpg",
  "people/src/assets/headshots/Creative_HeysuOh.jpg",
  "people/src/assets/headshots/Creative_SophiaHao.jpg",
  "people/src/assets/headshots/Creative_ShannonLee.jpg",
  "people/src/assets/headshots/Creative_SophieHeap.jpg",
  "people/src/assets/headshots/Creative_LeslieLin.jpg",
  "people/src/assets/headshots/Creative_YuerZhu.jpg",
  "people/src/assets/headshots/Creative_DionLewis.jpg",
  "people/src/assets/headshots/Creative_MicheleHratko.jpg",
  "people/src/assets/headshots/Creative_JoannaNi.jpg",
  "people/src/assets/headshots/Creative_PhoebeLee.jpg",
  "people/src/assets/headshots/Creative_ShannonLin.jpg",
  "people/src/assets/headshots/Creative_JeffreyYe.jpg",
  "people/src/assets/headshots/Creative_AarnavPatel.jpg",
  "people/src/assets/headshots/Creative_JingPeng.jpg",
  "people/src/assets/headshots/Creative_MasonWang.jpg",
  "people/src/assets/headshots/Creative_SuannaZhong.jpg",
  "people/src/assets/headshots/Creative_ErinHsu.jpg",
  "people/src/assets/headshots/Creative_EuniceLai.jpg",
  "people/src/assets/headshots/Creative_PerryChen.jpg",
  "people/src/assets/headshots/Creative_OscarWang.jpg",
  "people/src/assets/headshots/Creative_MatthewAkuamoah-Boateng.jpg",
  "people/src/assets/headshots/Creative_NicholasBaek.jpg",
  "people/src/assets/headshots/Creative_SherryChen.jpg",
  "people/src/assets/headshots/Creative_YonMaor.jpg",
  "people/src/assets/headshots/Creative_ChrisSong.jpg",
  "people/src/assets/headshots/Creative_StacyChen.jpg",
  "people/src/assets/headshots/Creative_AydenXu.jpg",
  "people/src/assets/headshots/Creative_ErvinSong.jpg",
  "people/src/assets/headshots/Creative_VivianaStaicu.jpg",
  "people/src/assets/headshots/Creative_EricLin.jpg",
  "people/src/assets/headshots/Creative_MinsungKang.jpg",
  "people/src/assets/headshots/PR_LillianHao.jpg",
  "people/src/assets/headshots/PR_PeggyShen.jpg",
  "people/src/assets/headshots/PR_AngelaHuang.jpg",
  "people/src/assets/headshots/PR_JiaxinLin.jpg",
  "people/src/assets/headshots/PR_JoelleLee.jpg",
  "people/src/assets/headshots/PR_KirstenPark.jpg",
  "people/src/assets/headshots/Design_AmyHu.png",
  "people/src/assets/headshots/Design_AmandaWen.png",
  "people/src/assets/headshots/Design_JuliaKasper.png",
  "people/src/assets/headshots/Design_MichaelDiGiovanna.png",
  "people/src/assets/headshots/Design_SaeraKim.png",
  "people/src/assets/headshots/Design_MinjooKim.png",
  "people/src/assets/headshots/Design_NayanaBalusu.png",
  "people/src/assets/headshots/Design_BrookeSchwartz.png",
  "people/src/assets/headshots/Design_GwenToll.png",
  "people/src/assets/headshots/Design_SueahKim.png",
  "people/src/assets/headshots/Design_LeaDeVylder.png",
  "people/src/assets/headshots/Design_KatrinaDarms.png",
  "people/src/assets/headshots/Design_SydneySun.png",
  "people/src/assets/headshots/Design_ClarineLee.png",
  "people/src/assets/headshots/Design_AnikaBhagavatula.png",
  "people/src/assets/headshots/Design_HazelFroling.png",
  "people/src/assets/headshots/Design_GraceKolosek.png",
  "people/src/assets/headshots/Design_CelineMin.png",
  "people/src/assets/headshots/Design_MayaGalindo Benson.png",
  "people/src/assets/headshots/Design_NicoleHuang.png",
  "people/src/assets/headshots/Design_SukieWang.png",
  "people/src/assets/headshots/Design_JacksonUnderwood.png",
  "people/src/assets/headshots/Design_RayyaGracy.png",
  "people/src/assets/headshots/Design_GraanaKhan.png",
  "people/src/assets/headshots/Design_CamelliaWang.png",
  "people/src/assets/headshots/Design_LilyDu.png",
  "people/src/assets/headshots/Model_JeffreyZhang.jpg",
  "people/src/assets/headshots/Model_BrookeGunter.jpg",
  "people/src/assets/headshots/Model_AnnaGerchanovsky.jpg",
  "people/src/assets/headshots/Model_YaninaShavialenka.jpg",
  "people/src/assets/headshots/Model_AndrewZhou.jpg",
  "people/src/assets/headshots/Model_MarissaFernandez.jpg",
  "people/src/assets/headshots/Model_TimothyKim.jpg",
  "people/src/assets/headshots/Model_MayaOusachi.jpg",
  "people/src/assets/headshots/Model_ElizabethHager.jpg",
  "people/src/assets/headshots/Model_JoyLeung.jpg",
  "people/src/assets/headshots/Model_KevinTong.jpg",
  "people/src/assets/headshots/Model_DunnZhang.jpg",
  "people/src/assets/headshots/Model_DestiniBrown-Greene.jpg",
  "people/src/assets/headshots/Model_MildredAmofa.jpg",
  "people/src/assets/headshots/Model_LucyHwang.jpg",
  "people/src/assets/headshots/Model_JocelynSu.jpg",
  "people/src/assets/headshots/Model_CarolineLaPiana.jpg",
  "people/src/assets/headshots/Model_SallyPak.jpg",
  "people/src/assets/headshots/Model_DhrutiKuchibhotla.jpg",
  "people/src/assets/headshots/Model_Olu-BankeBoakye-Yiadom.jpg",
  "people/src/assets/headshots/Hair_Makeup_TippiLi.jpeg",
  "people/src/assets/headshots/Hair_Makeup_AnnieWoo.jpeg",
  "people/src/assets/headshots/Hair_Makeup_DaniPreston.jpeg",
  "people/src/assets/headshots/Hair_Makeup_LaylaMalhas.jpeg",
  "people/src/assets/headshots/Hair_Makeup_JessicaLai.jpeg",
  "people/src/assets/headshots/Hair_Makeup_GraceLiao.jpeg",
  "people/src/assets/headshots/Hair_Makeup_MairssaLee.jpeg",
  "people/src/assets/headshots/Hair_Makeup_SulliYatabe.jpeg",
  "people/src/assets/headshots/Dance_JisooHan.jpg",
  "people/src/assets/headshots/Dance_VeraZhong.jpg",
  "people/src/assets/headshots/Dance_FranStedman.jpg",
  "people/src/assets/headshots/Dance_AlisaLo.jpg",
  "people/src/assets/headshots/Dance_SaanikaChauk.jpg",
  "people/src/assets/headshots/Dance_KaitlynXie.jpg",
  "people/src/assets/headshots/Dance_LiannaHuang.jpg",
  "people/src/assets/headshots/Dance_ChaseGumbs.jpg",
  "people/src/assets/headshots/Dance_AJSeo.jpg",
  "people/src/assets/headshots/Dance_HelenHuang.jpg",
  "people/src/assets/headshots/Dance_KellyDam.jpg",
  "people/src/assets/headshots/Dance_YujunWu.jpg",
  "people/src/assets/headshots/Dance_CindyLiu.jpg",
  "people/src/assets/headshots/Dance_JoannaGe.jpg",
  "people/src/assets/headshots/Dance_FranStedman.jpg",
  "people/src/assets/headshots/Dance_SmritiChopra.jpg",
  "people/src/assets/headshots/Dance_HannaLuo.jpg",
  "people/src/assets/headshots/Dance_AnnikaWu.jpg",
  "people/src/assets/headshots/Dance_AliceAnie.jpg",
  "people/src/assets/headshots/Dance_KateLee.jpg",
  "people/src/assets/headshots/Dance_SharonRen.jpg",
  "people/src/assets/headshots/Dance_SophiaHoch.jpg",
  "people/src/assets/headshots/Dance_CarolineMichalow.jpg",
  "people/src/assets/headshots/Dance_YuXiLee.jpg",
  "people/src/assets/headshots/Dance_LaurenLoriaSklar.jpg",
  "people/src/assets/headshots/Dance_SamanthaVu.jpg",
  "people/src/assets/headshots/Dance_IancaDeLosSantos.jpg",
  "people/src/assets/headshots/Dance_LilyStern.jpg",
  "people/src/assets/headshots/Dance_VeraMazeeva.jpg",
  "people/src/assets/headshots/Dance_AudreyShao.jpg",
  "people/src/assets/headshots/Dance_BrooklynMao.jpg",
  "people/src/assets/headshots/Dance_RebeccaJiang.jpg",
  "people/src/assets/headshots/Dance_RoyPark.jpg",
  "people/src/assets/headshots/Dance_KyliHilaire.jpg",
  "people/src/assets/headshots/Dance_ElvaJia.jpg",
  "people/src/assets/headshots/Dance_AnnikaWu.jpg",
  "people/src/assets/headshots/Dance_YikunYang.jpg",
];
